import PDFDocument from 'pdfkit';

function safeText(value, fallback = '') {
  const text = String(value ?? fallback).trim();
  return text || fallback;
}

function addLabeledLine(doc, label, value, y) {
  doc.fontSize(10).fillColor('#6b7280').text(label, 56, y, { width: 120 });
  doc
    .fontSize(16)
    .fillColor('#111827')
    .text(value, 56, y + 14, { width: 480 });
}

export async function renderCertificatePdf({ event, attendee, code, issuedAt, verifyUrl } = {}) {
  const doc = new PDFDocument({
    size: 'A4',
    margin: 48,
    compress: false,
    info: {
      Title: `Certificate ${code || ''}`.trim(),
      Author: 'NexaSphere',
      Subject: 'Event certificate',
    },
  });

  const chunks = [];
  doc.on('data', (chunk) => chunks.push(chunk));

  const completionDate = issuedAt ? new Date(issuedAt) : new Date();
  const completionLabel = Number.isNaN(completionDate.getTime())
    ? 'Issued recently'
    : completionDate.toLocaleDateString();

  doc.roundedRect(32, 32, 530, 770, 24).fillAndStroke('#f8fafc', '#dbeafe');

  doc
    .fillColor('#0f172a')
    .fontSize(28)
    .font('Helvetica-Bold')
    .text('Certificate of Completion', 56, 76);

  doc
    .fillColor('#334155')
    .fontSize(13)
    .font('Helvetica')
    .text('This certificate confirms successful participation in the NexaSphere event.', 56, 116, {
      width: 470,
      lineGap: 4,
    });

  doc.moveTo(56, 152).lineTo(504, 152).strokeColor('#bfdbfe').lineWidth(1.2).stroke();

  addLabeledLine(
    doc,
    'Awarded to',
    safeText(attendee?.name || attendee?.full_name || attendee?.email, 'Participant'),
    184
  );
  addLabeledLine(doc, 'Event', safeText(event?.name, 'NexaSphere Event'), 248);
  addLabeledLine(doc, 'Certificate Code', safeText(code, 'PENDING'), 312);
  addLabeledLine(doc, 'Issued On', completionLabel, 376);

  doc.fillColor('#475569').fontSize(11).text('Completion Details', 56, 452, { underline: true });
  doc
    .fillColor('#111827')
    .fontSize(12)
    .text(
      safeText(
        event?.description ||
          'Attendance and completion were verified through the NexaSphere event workflow.',
        'Attendance and completion were verified through the NexaSphere event workflow.'
      ),
      56,
      474,
      { width: 470, lineGap: 4 }
    );

  if (verifyUrl) {
    doc
      .fillColor('#2563eb')
      .fontSize(11)
      .text(`Verify online: ${verifyUrl}`, 56, 612, { width: 470 });
  }

  doc
    .fillColor('#64748b')
    .fontSize(9)
    .text('Generated by NexaSphere automated certificate workflow.', 56, 708, {
      align: 'center',
      width: 470,
    });

  doc.end();

  return await new Promise((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}
